// "use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/Shared/NavBar/NavBar";
import Footer from "@/components/Shared/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";

// import { Toaster } from "react-hot-toast";
// import Nav from "@/app/components/Nav";

import NextAuthProvider from "@/providers/NextAuthProvider";
import useHideNavbar from "./admin-dashboard/navbarControl/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  //  const hideNavbar = useHideNavbar();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar></NavBar>
            <main className=" flex-1"> {children}</main>
            <Toaster richColors />
            <Footer></Footer>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
